"""new

Revision ID: 1586112aad9b
Revises: 231dfd0ce9dc
Create Date: 2023-02-06 14:33:45.163102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1586112aad9b'
down_revision = '231dfd0ce9dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
