"""01_initial_migration

Revision ID: 177a17b97091
Revises: 
Create Date: 2023-02-18 20:32:39.784538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '177a17b97091'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.add_column('ticket_comments', sa.Column('is_edited', sa.Boolean(), server_default='f', nullable=False))
    op.drop_constraint('ticket_comments_text_key', 'ticket_comments', type_='unique')
    op.create_foreign_key(None, 'ticket_comments', 'users', ['author_id'], ['id'])
    op.create_foreign_key(None, 'tickets', 'users', ['reporter_id'], ['id'])
    op.create_foreign_key(None, 'tickets', 'users', ['assignee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'ticket_comments', type_='foreignkey')
    op.create_unique_constraint('ticket_comments_text_key', 'ticket_comments', ['text'])
    op.drop_column('ticket_comments', 'is_edited')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
