"""second

Revision ID: 3e52fff48946
Revises: 
Create Date: 2023-02-01 11:08:52.230647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e52fff48946'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_posts',
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=350), nullable=True),
    sa.Column('time_estimate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    op.create_index(op.f('ix_ticket_posts_ticket_id'), 'ticket_posts', ['ticket_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_posts_ticket_id'), table_name='ticket_posts')
    op.drop_table('ticket_posts')
    # ### end Alembic commands ###
