"""02_initial_migration

Revision ID: 44d6995aea0d
Revises: 378ad373c351
Create Date: 2023-02-15 11:00:57.204083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44d6995aea0d'
down_revision = '378ad373c351'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ticket_comments_text_key', 'ticket_comments', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('ticket_comments_text_key', 'ticket_comments', ['text'])
    # ### end Alembic commands ###
