"""add hash User

Revision ID: 729846e15f6b
Revises: 97738ba63980
Create Date: 2023-03-07 13:37:11.022919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '729846e15f6b'
down_revision = '97738ba63980'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hash', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hash')
    # ### end Alembic commands ###
