"""three

Revision ID: 8e48555fd859
Revises: f82f8637c053
Create Date: 2023-02-01 12:16:04.920593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e48555fd859'
down_revision = 'f82f8637c053'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_posts', sa.Column('assignee', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ticket_posts', 'employees', ['assignee'], ['employees_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ticket_posts', type_='foreignkey')
    op.drop_column('ticket_posts', 'assignee')
    # ### end Alembic commands ###
