"""02_add_title_to_ticket

Revision ID: 97738ba63980
Revises: cb0cf36642d1
Create Date: 2023-02-25 22:26:03.427171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97738ba63980'
down_revision = 'cb0cf36642d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'ticket_priorities', ['title'])
    op.create_unique_constraint(None, 'ticket_statuses', ['title'])
    op.create_unique_constraint(None, 'ticket_types', ['title'])
    op.add_column('tickets', sa.Column('title', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'title')
    op.drop_constraint(None, 'ticket_types', type_='unique')
    op.drop_constraint(None, 'ticket_statuses', type_='unique')
    op.drop_constraint(None, 'ticket_priorities', type_='unique')
    # ### end Alembic commands ###
