"""cascade

Revision ID: a43b9e5c4fab
Revises: 15e6549a929d
Create Date: 2023-05-05 18:53:43.631989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a43b9e5c4fab'
down_revision = '15e6549a929d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('boards_creator_email_fkey', 'boards', type_='foreignkey')
    op.create_foreign_key(None, 'boards', 'users', ['creator_email'], ['email'], ondelete='CASCADE')
    op.drop_constraint('ticket_comments_author_email_fkey', 'ticket_comments', type_='foreignkey')
    op.create_foreign_key(None, 'ticket_comments', 'users', ['author_email'], ['email'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'ticket_priorities', ['title'])
    op.create_unique_constraint(None, 'ticket_types', ['title'])
    op.drop_constraint('tickets_reporter_email_fkey', 'tickets', type_='foreignkey')
    op.drop_constraint('tickets_assignee_email_fkey', 'tickets', type_='foreignkey')
    op.create_foreign_key(None, 'tickets', 'users', ['reporter_email'], ['email'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tickets', 'users', ['assignee_email'], ['email'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.create_foreign_key('tickets_assignee_email_fkey', 'tickets', 'users', ['assignee_email'], ['email'])
    op.create_foreign_key('tickets_reporter_email_fkey', 'tickets', 'users', ['reporter_email'], ['email'])
    op.drop_constraint(None, 'ticket_types', type_='unique')
    op.drop_constraint(None, 'ticket_priorities', type_='unique')
    op.drop_constraint(None, 'ticket_comments', type_='foreignkey')
    op.create_foreign_key('ticket_comments_author_email_fkey', 'ticket_comments', 'users', ['author_email'], ['email'])
    op.drop_constraint(None, 'boards', type_='foreignkey')
    op.create_foreign_key('boards_creator_email_fkey', 'boards', 'users', ['creator_email'], ['email'])
    # ### end Alembic commands ###
