"""03_initial_migration

Revision ID: aeb0d2a538b1
Revises: 44d6995aea0d
Create Date: 2023-02-17 19:25:15.018808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeb0d2a538b1'
down_revision = '44d6995aea0d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
