"""three

Revision ID: b3213313a525
Revises: 8e48555fd859
Create Date: 2023-02-04 01:16:20.704305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3213313a525'
down_revision = '8e48555fd859'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('Comments_name', sa.String(length=350), nullable=True))
    op.drop_constraint('comments_FComments_name_key', 'comments', type_='unique')
    op.create_unique_constraint(None, 'comments', ['Comments_name'])
    op.drop_column('comments', 'FComments_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('FComments_name', sa.VARCHAR(length=350), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comments', type_='unique')
    op.create_unique_constraint('comments_FComments_name_key', 'comments', ['FComments_name'])
    op.drop_column('comments', 'Comments_name')
    # ### end Alembic commands ###
