"""update model

Revision ID: c97fa18693ac
Revises: da714d75141a
Create Date: 2023-02-05 01:54:43.153471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c97fa18693ac'
down_revision = 'da714d75141a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_comments', sa.Column('text', sa.String(length=350), nullable=True))
    op.add_column('ticket_comments', sa.Column('author_id', sa.Integer(), nullable=True))
    op.add_column('ticket_comments', sa.Column('creation_date', sa.DateTime(), nullable=True))
    op.drop_constraint('ticket_comments_name_key', 'ticket_comments', type_='unique')
    op.create_unique_constraint(None, 'ticket_comments', ['text'])
    op.create_foreign_key(None, 'ticket_comments', 'employees', ['author_id'], ['id'])
    op.drop_column('ticket_comments', 'name')
    op.add_column('tickets', sa.Column('creation_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'creation_date')
    op.add_column('ticket_comments', sa.Column('name', sa.VARCHAR(length=350), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ticket_comments', type_='foreignkey')
    op.drop_constraint(None, 'ticket_comments', type_='unique')
    op.create_unique_constraint('ticket_comments_name_key', 'ticket_comments', ['name'])
    op.drop_column('ticket_comments', 'creation_date')
    op.drop_column('ticket_comments', 'author_id')
    op.drop_column('ticket_comments', 'text')
    # ### end Alembic commands ###
