"""01_initial_migration

Revision ID: cb0cf36642d1
Revises: 
Create Date: 2023-02-25 20:36:23.362588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb0cf36642d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_priorities',
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('title'),
    sa.UniqueConstraint('title')
    )
    op.create_table('ticket_statuses',
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('title'),
    sa.UniqueConstraint('title')
    )
    op.create_table('ticket_types',
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('title'),
    sa.UniqueConstraint('title')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('creation_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_estimate', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.String(length=64), nullable=True),
    sa.Column('ttype', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('reporter_email', sa.String(length=64), nullable=True),
    sa.Column('assignee_email', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['assignee_email'], ['users.email'], ),
    sa.ForeignKeyConstraint(['priority'], ['ticket_priorities.title'], ),
    sa.ForeignKeyConstraint(['reporter_email'], ['users.email'], ),
    sa.ForeignKeyConstraint(['status'], ['ticket_statuses.title'], ),
    sa.ForeignKeyConstraint(['ttype'], ['ticket_types.title'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_id'), 'tickets', ['id'], unique=True)
    op.create_table('ticket_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(length=256), nullable=True),
    sa.Column('author_email', sa.String(length=64), nullable=True),
    sa.Column('creation_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_edited', sa.Boolean(), server_default='f', nullable=False),
    sa.ForeignKeyConstraint(['author_email'], ['users.email'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_comments_id'), 'ticket_comments', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_comments_id'), table_name='ticket_comments')
    op.drop_table('ticket_comments')
    op.drop_index(op.f('ix_tickets_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('ticket_types')
    op.drop_table('ticket_statuses')
    op.drop_table('ticket_priorities')
    # ### end Alembic commands ###
