"""new

Revision ID: ec66d5ace89b
Revises: 1586112aad9b
Create Date: 2023-02-06 15:40:27.019469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec66d5ace89b'
down_revision = '1586112aad9b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
